### ISSUE TITLE
When will the next release of CPU jitter occur?

### ISSUE THREAD

**Issue by darylmartin100** [smuellerDD/jitterentropy-library#130]
We are looking to upgrade our version of CPU Jitter to your next release (3.7.0) so we can consume https://github.com/smuellerDD/jitterentropy-library/pull/125.  Do you have a rough idea when you will do another release?

Thanks!

**Comment by smuellerDD** [comment]
Am Donnerstag, 21. November 2024, 01:46:20 Mitteleuropäische Normalzeit 
schrieb Daryl Martin:

Hi Daryl,

> We are looking to upgrade our version of CPU Jitter to your next release
> (3.7.0) so we can consume
> https://github.com/smuellerDD/jitterentropy-library/pull/125.  Do you have
> a rough idea when you will do another release?
> 
> Thanks!

Do you need that patch? If so, I can certainly make a release, but this would 
be a 3.6.1 because so far, there is no patch so far that changes anything in 
the entropy collection or management.

Ciao
Stephan

**Comment by darylmartin100** [comment]
A patch (3.6.1) would be greatly appreciated.  We want to use a released version in AWS-LC for our next major release.

**Comment by smuellerDD** [comment]
Released
