### ISSUE TITLE
Questions on seeeding, value of similar utilities

### ISSUE THREAD

**Issue by HulaHoop0** [smuellerDD/jitterentropy-library#16]
Hi Stephan. I was wondering if adding more entropy gathering daemons (haveged,twuewand and timer_entropyd) that use cpu jitter as their source too, actually increases the real system entropy? Does the unique algo used by each help?

We are considering twuewand to combat the problem of distros enabling trust of hw cpu rngs which in some cases are broken and output repeating numbers, if malicious outright. We are especially worried about the quality of the initial seed. Does jitterentropy help in this case?

cc/ @adrelanos

**Comment by smuellerDD** [comment]
Am Sonntag, 2. Februar 2020, 19:21:00 CET schrieb HulaHoop0:

Hi HulaHoop0,

> Hi Stephan. I was wondering if adding more entropy gathering daemons
> (haveged,twuewand and timer_entropyd) that use cpu jitter as their source
> too, actually increases the real system entropy?

As I am not fully sure how the others are implemented, I cannot fully comment 
on those.

But let us assume we have, say, 3 Jitter RNG instances running in parallel. 
Each of it generates a full amount of entropy as the noise source acts 
independently from the operation of any other process, including another 
Jitter RNG instance as outlined in my document.

So, having 3 Jitter RNG running in parallel provides the same amount of 
entropy as having one Jitter RNG providing as much data as the other 3 
together. So, their entropy is additive.

Nonetheless, I am not sure why you want to run 3 instances here: the Jitter 
RNG (and I guess the other two implementations) are just postprocessing 
operations using (I speculate) the same noise source. In this case, all you 
can protect yourself against is a failure in the postprocessing operation, but 
not a failure in the actual noise source. Please note that the postprocessing 
does not add or provide entropy, it only harvests it and compresses it (and 
potentially looses entropy in the compression process).

> Does the unique algo used
> by each help?

As outlined above and speaking of the Jitter RNG only, whether you run 3 
instances or one instance and gather three times the amount of data is equal.

The only benefit from running 3 instances is that you may gather the data 
faster as you (may) use multiple CPUs now.
> 
> We are considering twuewand to combat the problem of distros enabling trust
> of hw cpu rngs which in some cases are broken and output repeating numbers,
> if malicious outright. We are especially worried about the quality of the
> initial seed. Does jitterentropy help in this case?

I guess your concern is that RDRAND and similar are broken (as it was 
demonstrated for some AMD CPUs) and that the /dev/urandom or getrandom(2) is 
considered fully seeded from RDRAND and friends.

In this case, I hope so that my Jitter RNG provides additional entropy to 
mitigate this issue :-)

The only requirement would be that the Jitter RNG instance needs to start 
before any crypto "user" starts. I.e. if you use the jitterentropy-rngd, make 
sure it starts as early as possible in the boot chain. Maybe you even start it 
in the initramfs phase considering its binary has no dependencies.


Ciao
Stephan

**Comment by adrelanos** [comment]
Thanks, Stephan! That is good to know.

twuewand as far as I understand isn't jitter based. It is using truerand algorithm. Quote:

> twuewand is software that creates hardware-generated random data. It accomplishes this by exploiting the fact that the CPU clock and the RTC (real-time clock) are physically separate, and that time and work are not linked.

sources:

* https://www.finnie.org/software/twuewand/
* https://www.finnie.org/2011/09/25/introducing-twuewand/
* https://www.finnie.org/2012/08/14/twuewand-2-0-released/

I am working on packaging for Debian and integration for installation by default:

* https://forums.whonix.org/t/twuewand-a-truerand-algorithm-for-generating-entropy-whonix-integration/8880
* https://www.whonix.org/wiki/Dev/Entropy#twuewand_-_a_truerand_algorithm_for_generating_entropy

Currently trying to wrap figure out around all the different options for entropy gathering.

* https://www.whonix.org/wiki/Dev/Entropy

Listing, categorizing all the various entropy generators and making notes which ones could be useful for us:

https://www.whonix.org/wiki/Dev/Entropy#Software_Packages

Jitter RNG is amazing! Through installing the Debian jitterentropy-rng package by default we gained easy access to an entropy source at ultra low maintenance effort at our Debian derivative level.

Our plan is to gather entropy from as many diverse sources (preferred) as possible. Since we're maintaining Linux distributions (Whonix and Kicksecure), we're focusing on software solutions that we can package, pre-configure and pre-install by default for our users.

We might also use the same entropy source twice using a different algorithm. Such as CPU through jitter (jitterentropy-rng) and twuewand (truerand algorithm using CPU and RTC). If that makes sense? Using the same entropy source twice isn't the preferred solution but we might easily run out of things we can do in user space that works for our users easily and out of the box.

(Hardware entropy generators might work great but I don't many will go for it and properly set it up. Also, I'd see them again as addition and not replacement for software based entropy sources.)

randomsound looks also promising for that purpose.

* https://www.whonix.org/wiki/Dev/Entropy#randomsound
* https://www.whonix.org/pipermail/whonix-devel/2020-February/001509.html

RDRAND set to distrusted already:

https://www.whonix.org/wiki/Dev/Entropy#RDRAND

**Comment by smuellerDD** [comment]
Am Montag, 3. Februar 2020, 14:22:25 CET schrieb Patrick Schleizer:

Hi Patrick,

> Thanks, Stephan! That is good to know.
> 
> twuewand as far as I understand isn't jitter based. It is using truerand 
algorithm. Quote:
> > twuewand is software that creates hardware-generated random data. It
> > accomplishes this by exploiting the fact that the CPU clock and the RTC
> > (real-time clock) are physically separate, and that time and work are not
> > linked.
> sources:
> 
> * https://www.finnie.org/software/twuewand/
> * https://www.finnie.org/2011/09/25/introducing-twuewand/
> * https://www.finnie.org/2012/08/14/twuewand-2-0-released/
> 
> I am working on packaging for Debian and integration for installation by
> default:
> 
> *
> https://forums.whonix.org/t/twuewand-a-truerand-algorithm-for-generating-en
> tropy-whonix-integration/8880 *
> https://www.whonix.org/wiki/Dev/Entropy#twuewand_-_a_truerand_algorithm_for
> _generating_entropy
> 
> Currently trying to wrap figure out around all the different options for
> entropy gathering.

Thanks for the pointers. I need to dig into them.
> 
> * https://www.whonix.org/wiki/Dev/Entropy
> 
> Listing, categorizing all the various entropy generators and making notes
> which ones could be useful for us:
> 
> https://www.whonix.org/wiki/Dev/Entropy#Software_Packages
> 
> Jitter RNG is amazing! Through installing the Debian jitterentropy-rng
> package by default we gained easy access to an entropy source at ultra low
> maintenance effort at our Debian derivative level.

Nice to hear.
> 
> Our plan is to gather entropy from as many diverse sources (preferred) as
> possible. Since we're maintaining Linux distributions (Whonix and
> Kicksecure), we're focusing on software solutions that we can package,
> pre-configure and pre-install by default for our users.

The more noise sources, the better.
> 
> We might also use the same entropy source twice using a different algorithm.
> Such as CPU through jitter (jitterentropy-rng) and twuewand (truerand
> algorithm using CPU and RTC). If that makes sense?

Assuming that twuewand is conceptually similar to my Jitter RNG, then all you 
get from running both is the assurance if one of the algorithmic parts (i.e. 
the part that does not provide entropy but only compresses and potentially 
looses it) fails, the other helps. But it does not guard against a noise 
source failure which is usually the issue you want to guard against.

> Using the same entropy
> source twice isn't the preferred solution but we might easily run out of
> things we can do in user space that works for our users easily and out of
> the box.
> 
> (Hardware entropy generators might work great but I don't many will go for
> it and properly set it up. Also, I'd see them again as addition and not
> replacement for software based entropy sources.)
> 
> randomsound looks also promising for that purpose.
> 
> * https://www.whonix.org/wiki/Dev/Entropy#randomsound
> * https://www.whonix.org/pipermail/whonix-devel/2020-February/001509.html

I have heard of that, but did not check it closely.
> 
> RDRAND set to distrusted already:
> 
> https://www.whonix.org/wiki/Dev/Entropy#RDRAND

Ciao
Stephan

**Comment by adrelanos** [comment]
Is debiasing / whitening nowadays for entropy gathering daemons running in userspace is still important or a waste of system resources? What I mean by that...

----

example from:

* https://packages.debian.org/buster/randomsound
* https://github.com/adrelanos/randomsound
* https://github.com/adrelanos/randomsound/blob/master/debias.c

```
/** @file debias.c
 *
 * Implementation of a von-neumann debiassing of a random bitstream.
 */

#include "debias.h"

int
transfer_bits_and_debias(BitBuffer from, BitBuffer to)
{
  BitField bits;
  int bits_xfered = 0;
  while (bitbuffer_available_bits(from) >= 2) {
    if (bitbuffer_extract_bits(from, &bits, 2) != 2)
      return bits_xfered;
    if ((bits & 3) == 1 || (bits & 3) == 2) {
      if (bitbuffer_add_bits(to, bits, 1) != 1)
        return bits_xfered;
      bits_xfered++;
    }
  }
  return bits_xfered;
}
```

----

example from twuewand:

* https://www.finnie.org/software/twuewand/
* https://github.com/rfinnie/twuewand
* https://www.finnie.org/2011/09/25/introducing-twuewand/
* https://www.finnie.org/2012/08/14/twuewand-2-0-released/
* https://forums.whonix.org/t/twuewand-a-truerand-algorithm-for-generating-entropy-whonix-integration/8880

```
    def process_von_neumann(self):
        # Apply Von Neumann to incoming bits
        self.raw_byte_queue.extend(self.incoming_bytes)
        for byte in self.incoming_bytes:
            for i in (0, 2, 4, 6):
                bit1 = (byte >> i) & 1
                bit2 = (byte >> (i + 1)) & 1
                if bit1 == bit2:
                    continue
                self.vn_partial_byte = (self.vn_partial_byte << 1) + bit1
                self.vn_partial_byte_bits += 1
                self.bits_generated += 1
                if self.vn_partial_byte_bits == 8:
                    self.vn_byte_queue.append(self.vn_partial_byte)
                    self.vn_partial_byte = 0
                    self.vn_partial_byte_bits = 0
        self.incoming_bytes = bytearray()
```

```
    def process_kaminsky(self):
        # Every 32 bytes of Von Neumann data, AES encrypt
        while len(self.vn_byte_queue) >= 32:
            # All raw bits are fed to the SHA256 hash
            self.kaminsky_hash.update(bytes(self.raw_byte_queue))
            self.raw_byte_queue = bytearray()

            key = self.kaminsky_hash.copy().digest()
            a = AES.new(key, AES.MODE_ECB)
            self.output_queue.extend(a.encrypt(bytes(self.vn_byte_queue[0:32])))
            self.vn_byte_queue = self.vn_byte_queue[32:]
```

```
    def process_sha256(self):
        # Further whiten Von Neumann data with SHA256
        while len(self.vn_byte_queue) >= 32:
            self.raw_byte_queue = bytearray()

            h = hashlib.sha256()
            h.update(bytes(self.vn_byte_queue[0:32]))
            self.output_queue.extend(h.digest())
            self.vn_byte_queue = self.vn_byte_queue[32:]
```

Quote [wikipedia](https://en.wikipedia.org/wiki//dev/random):

> In January 2014, Daniel J. Bernstein published a [critique](https://blog.cr.yp.to/20140205-entropy.html) of how Linux mixes different sources of entropy. He outlines an attack in which one source of entropy capable of monitoring the other sources of entropy could modify its output to nullify the randomness of the other sources of entropy.

Has this been fixed since?

I guess yes? /dev/random is still world-writeable by any unprivileged user. Simply writing to /dev/entropy should never worsen entropy quality, so the current understanding goes.

At least as long as ioctl(2), RNDADDENTROPY is not being used. Using RNDADDENTROPY might worsen things?

Let's assume RNDADDENTROPY isn't used.

By that logic, there is no need debiasing / whitening of output from any userspace entropy gathering daemons since the kernel will fix that for us anyhow? I am asking because debiasing / whitening costs a lot CPU use. twuewand becomes slower. I don't know the exact factor but it is likely a multiple. It has a `--nodebias` parameter which I would be eager to pass if the kernel doesn't require higher quality written to /dev/random. I can't quantify things yet (yet have to do random testing using ent, rngtest, dieharder) but I guess feeding a lot low quality entropy into /dev/random than a bit high quality then we can skip the extra CPU cycles and go for a lot low quality entropy since the kernel will benefit from it more?

**Comment by smuellerDD** [comment]
Am Dienstag, 4. Februar 2020, 12:18:55 CET schrieb Patrick Schleizer:

Hi Patrick,

> Is debiasing / whitening nowadays for entropy gathering daemons running in
> userspace is still important or a waste of system resources? What I mean by
> that...

A Von-Neumann unbiaser is good IFF we have stochastically independent values. 
Otherwise, a Von-Neumann unbiaser can be a disaster. Such independence, 
however, is commonly not given.

Thus, I would not recommend it. If you have a skew somehow, rather use a 
cryptographic function like, well, an RNG to eliminate the skew. In case your 
output of the noise source conditioning operation has a skew, then one need to 
pull a bit more data depending on your entropy analysis to seed the RNG.
> 
> ----
> 
> example from:
> 
> * https://packages.debian.org/buster/randomsound
> * https://github.com/adrelanos/randomsound
> * https://github.com/adrelanos/randomsound/blob/master/debias.c
> 
> ```
> /** @file debias.c
>  *
>  * Implementation of a von-neumann debiassing of a random bitstream.
>  */
> 
> #include "debias.h"
> 
> int
> transfer_bits_and_debias(BitBuffer from, BitBuffer to)
> {
>   BitField bits;
>   int bits_xfered = 0;
>   while (bitbuffer_available_bits(from) >= 2) {
>     if (bitbuffer_extract_bits(from, &bits, 2) != 2)
>       return bits_xfered;
>     if ((bits & 3) == 1 || (bits & 3) == 2) {
>       if (bitbuffer_add_bits(to, bits, 1) != 1)
>         return bits_xfered;
>       bits_xfered++;
>     }
>   }
>   return bits_xfered;
> }
> ```
> 
> ----
> 
> example from twuewand:
> 
> * https://www.finnie.org/software/twuewand/
> * https://github.com/rfinnie/twuewand
> * https://www.finnie.org/2011/09/25/introducing-twuewand/
> * https://www.finnie.org/2012/08/14/twuewand-2-0-released/
> *
> https://forums.whonix.org/t/twuewand-a-truerand-algorithm-for-generating-en
> tropy-whonix-integration/8880
> 
> ```
>     def process_von_neumann(self):
>         # Apply Von Neumann to incoming bits
>         self.raw_byte_queue.extend(self.incoming_bytes)
>         for byte in self.incoming_bytes:
>             for i in (0, 2, 4, 6):
>                 bit1 = (byte >> i) & 1
>                 bit2 = (byte >> (i + 1)) & 1
>                 if bit1 == bit2:
>                     continue
>                 self.vn_partial_byte = (self.vn_partial_byte << 1) + bit1
>                 self.vn_partial_byte_bits += 1
>                 self.bits_generated += 1
>                 if self.vn_partial_byte_bits == 8:
>                     self.vn_byte_queue.append(self.vn_partial_byte)
>                     self.vn_partial_byte = 0
>                     self.vn_partial_byte_bits = 0
>         self.incoming_bytes = bytearray()
> ```
> 
> ```
>     def process_kaminsky(self):
>         # Every 32 bytes of Von Neumann data, AES encrypt
>         while len(self.vn_byte_queue) >= 32:
>             # All raw bits are fed to the SHA256 hash
>             self.kaminsky_hash.update(bytes(self.raw_byte_queue))
>             self.raw_byte_queue = bytearray()
> 
>             key = self.kaminsky_hash.copy().digest()
>             a = AES.new(key, AES.MODE_ECB)
>            
> self.output_queue.extend(a.encrypt(bytes(self.vn_byte_queue[0:32])))
> self.vn_byte_queue = self.vn_byte_queue[32:]
> ```
> 
> ```
>     def process_sha256(self):
>         # Further whiten Von Neumann data with SHA256
>         while len(self.vn_byte_queue) >= 32:
>             self.raw_byte_queue = bytearray()
> 
>             h = hashlib.sha256()
>             h.update(bytes(self.vn_byte_queue[0:32]))
>             self.output_queue.extend(h.digest())
>             self.vn_byte_queue = self.vn_byte_queue[32:]
> ```
> 
> Quote [wikipedia](https://en.wikipedia.org/wiki//dev/random):
> > In January 2014, Daniel J. Bernstein published a
> > [critique](https://blog.cr.yp.to/20140205-entropy.html) of how Linux
> > mixes different sources of entropy. He outlines an attack in which one
> > source of entropy capable of monitoring the other sources of entropy
> > could modify its output to nullify the randomness of the other sources of
> > entropy.
> Has this been fixed since?
> 
> I guess yes? /dev/random is still world-writeable by any unprivileged user.
> Simply writing to /dev/entropy should never worsen entropy quality, so the
> current understanding goes.
> 
> At least as long as ioctl(2), RNDADDENTROPY is not being used. Using
> RNDADDENTROPY might worsen things?
> 
> Let's assume RNDADDENTROPY isn't used.
> 
> By that logic, there is no need debiasing / whitening of output from any
> userspace entropy gathering daemons since the kernel will fix that for us
> anyhow? I am asking because debiasing / whitening costs a lot CPU use.
> twuewand becomes slower. I don't know the exact factor but it is likely a
> multiple. It has a `--nodebias` parameter which I would be eager to pass if
> the kernel doesn't require higher quality written to /dev/random. I can't
> quantify things yet (yet have to do random testing using ent, rngtest,
> dieharder) but I guess feeding a lot low quality entropy into /dev/random
> than a bit high quality then we can skip the extra CPU cycles and go for a
> lot low quality entropy since the kernel will benefit from it more?



Ciao
Stephan

**Comment by adrelanos** [comment]
How would I know if any entropy generator produces stochastically
independent values?

**Comment by smuellerDD** [comment]
Am Donnerstag, 6. Februar 2020, 12:11:52 CET schrieb Patrick Schleizer:

Hi Patrick,

> How would I know if any entropy generator produces stochastically
> independent values?

Per default, assume that they are not independent. Only with an entropy 
analysis and a rationale why events should be stochastically independent you 
may assume that it is so.

Ciao
Stephan

**Comment by adrelanos** [comment]
Would it be useful for our upcoming [hardened-kernel](https://github.com/Whonix/hardened-kernel) / or generally to enable kernel config options `CONFIG_CRYPTO_ANSI_CPRNG`?

(`CONFIG_CRYPTO_ANSI_CPRNG=y`)

**Comment by smuellerDD** [comment]
Am Freitag, 21. Februar 2020, 12:03:08 CET schrieb Patrick Schleizer:

Hi Patrick,

> Would it be useful for our upcoming
> [hardened-kernel](https://github.com/Whonix/hardened-kernel) / or generally
> to enable kernel config options `CONFIG_CRYPTO_ANSI_CPRNG`?
> 
> (`CONFIG_CRYPTO_ANSI_CPRNG=y`)

This cipher is not really relevant any more - it is the ANSI X9.31 Appendix 
A2.4 RNG. The SP800-90A DRBGs are superior to the ANSI equivalent due to 
covering reseed requirements and similar.

I see no reason to have that RNG enabled.

Ciao
Stephan

**Comment by adrelanos** [comment]
We are using kernel command line `random.trust_cpu=off` to distrust / not credit randomness sourced from CPU's `RDRAND`. ([rationale](https://www.whonix.org/wiki/Dev/Entropy#RDRAND))

Now we are wondering about the following kernel compile configuration changes:

Old:

```
CONFIG_HW_RANDOM=m
CONFIG_HW_RANDOM_INTEL=m
CONFIG_HW_RANDOM_AMD=m
CONFIG_HW_RANDOM_VIA=m
```

New:

```
CONFIG_HW_RANDOM=y
CONFIG_HW_RANDOM_INTEL=y
CONFIG_HW_RANDOM_AMD=y
CONFIG_HW_RANDOM_VIA=y
```

Would that be a good idea?
(Presumption is: "don't trust/credit hwrng such as RDRAND but mix it into the randomness pool". ([rationale](https://www.whonix.org/wiki/Dev/Entropy#Write_to_.2Fdev.2Frandom)))

Would that contradict `random.trust_cpu=off`?

Does `random.trust_cpu=off` cover hardware random generators that are located at the motherboard and not inside the CPU? (`CONFIG_HW_RANDOM_VIA` says it is on the motherboard.)

Is `CONFIG_HW_RANDOM_INTEL` "same as" `RDRAND`? In other words, would `CONFIG_HW_RANDOM_INTEL=n` result in disabling `RDRAND`? (I am not suggesting to configure `CONFIG_HW_RANDOM_INTEL=n`. This is just for better understanding.)

My worry is that by having these hardware random generators load earlier than the module could be load could result in the initial random seeding to be more likely compromised if these hardware randomness generators are flawed / predictable / backdoored.

**Comment by smuellerDD** [comment]
Am Dienstag, 25. Februar 2020, 07:36:52 CET schrieb Patrick Schleizer:

Hi Patrick,

> We are using kernel command line `random.trust_cpu=off` to distrust / not
> credit randomness sourced from CPU's `RDRAND`.
> ([rationale](https://www.whonix.org/wiki/Dev/Entropy#RDRAND))
> 
> Now we are wondering about the following kernel compile configuration
> changes:
> 
> Old:
> 
> ```
> CONFIG_HW_RANDOM=m
> CONFIG_HW_RANDOM_INTEL=m
> CONFIG_HW_RANDOM_AMD=m
> CONFIG_HW_RANDOM_VIA=m
> ```
> 
> New:
> 
> ```
> CONFIG_HW_RANDOM=y
> CONFIG_HW_RANDOM_INTEL=y
> CONFIG_HW_RANDOM_AMD=y
> CONFIG_HW_RANDOM_VIA=y
> ```
> 
> Would that be a good idea?

For starters, this is the hardware RNG framework making hardware RNGs 
accessible via /dev/hwrand (code residing in drivers/char/hw_random).

The Intel RNG is a different RNG than RDRAND, but I am not fully sure which 
hardware component would provide it (I guess some form of chipset that even 
provides the QAT hardware crypto system).

If a HW RNG driver sets the struct hwrng->quality integer (which defines that 
it provides entropy), the HW RNG framework will deliver entropy via 
add_hwgenerator_randomness to /dev/random. Otherwise the /dev/random is not 
affected by the HW RNG framework and its drivers.

Just do a grep quality in the drivers dir to see which drivers set a value and 
thus would increase the entropy in /dev/random. Then decide for yourself 
whether you want that.


> (Presumption is: "don't trust/credit hwrng such as RDRAND but mix it into
> the randomness pool".
> ([rationale](https://www.whonix.org/wiki/Dev/Entropy#Write_to_.2Fdev.2Frand
> om)))
> 
> Would that contradict `random.trust_cpu=off`?

As stated above, it would not contradict it as the noise source would be 
completely different (dedicated hardware).
> 
> Does `random.trust_cpu=off` cover hardware random generators that are
> located at the motherboard and not inside the CPU? (`CONFIG_HW_RANDOM_VIA`
> says it is on the motherboard.)

No.
> 
> Is `CONFIG_HW_RANDOM_INTEL` "same as" `RDRAND`?

No, see above.

> In other words, would
> `CONFIG_HW_RANDOM_INTEL=n` result in disabling `RDRAND`? (I am not
> suggesting to configure `CONFIG_HW_RANDOM_INTEL=n`. This is just for better
> understanding.)
> 
> My worry is that by having these hardware random generators load earlier
> than the module could be load could result in the initial random seeding to
> be more likely compromised if these hardware randomness generators are
> flawed / predictable / backdoored.



Ciao
Stephan

**Comment by adrelanos** [comment]
You might find this discussion of twuewand interesting. @rfinnie

The owner of this repository, Stephan Mueller @smuellerDD is the author of jitterentropy-rng who also re-worked Linux kernel entropy.

https://www.chronox.de/jent.html

Also author of Documentation and Analysis of the Linux Random Number Generator, published on a German government website:
https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/Studies/LinuxRNG/LinuxRNG_EN.pdf

----

twuewand on github:
https://github.com/rfinnie/twuewand

**Comment by adrelanos** [comment]
https://www.chronox.de/jent/doc/CPU-Jitter-NPTRNG.html

----

truerand main source file (actual implementation):
https://github.com/rfinnie/twuewand/blob/main/twuewand/truerand.py

----

If I understand it right, on Linux, simplified, jitterentropy-rng uses "only" `clock_gettime CLOCK_REALTIME` but, twuewand effectively uses CPU `clock_gettime` `CLOCK_REALTIME` + wallclock / RTC `clock_gettime` `CLOCK_MONOTONIC` `CLOCK_MONOTONIC_RAW` or `CLOCK_BOOTTIME`?

If both are using `clock_gettime` `CLOCK_REALTIME` then failure of that noise source would break both entropy generators.

However, it still seems to make sense to run both at the same time since these would generate a different type entropy? Simplified, jitterentropy-rng comparing time from CPU with time from CPU and twuewand comparing time from CPU with time from RTC.
