### ISSUE TITLE
Questions on raw entropy

### ISSUE THREAD

**Issue by andyjjones28** [smuellerDD/jitterentropy-library#17]
Hi Stephan,

I have a question about the raw entropy tests described in section 7.1.1 (first dot point) of your paper.  The continuous raw test and raw restart tests produce data in two columns that look like this:

20595 15070
59930 15085
...

As I understand it, the first column comes from 2⁰ to 2⁴ iterations of the LFSR, and the second is fixed at 2⁰ iterations of the LFSR; and these are the upper and lower boundaries that you describe in your paper.

I want to analyze this data using the [SP800-90B EntropyAssessment](https://github.com/usnistgov/SP800-90B_EntropyAssessment) tools.

Should I be analyzing these files with two columns as-is, or should I be splitting the upper and lower bounds and analyzing them separately?

Thanks so much for your help Stephan.
Regards,
Andrew

**Comment by smuellerDD** [comment]
Am Donnerstag, 3. September 2020, 05:34:35 CEST schrieb andyjjones28:

Hi andyjjones28,

> Hi Stephan,
> 
> I have a question about the raw entropy tests described in section 7.1.1
> (first dot point) of your paper.  The continuous raw test, and the raw
> restart tests produce data in two columns that look like this:
 
> 20595 15070
> 59930 15085
> ...
> 
> As I understand it, the first column comes from 2⁰ to 2⁴ iterations of the
> LFSR, and the second is fixed at 2⁰ iterations of the LFSR; and these are
> the upper and lower boundaries that you describe in your paper.

Precisely.
 
> I want to analyze this data using the [SP800-90B
> EntropyAssessment](https://github.com/usnistgov/SP800-90B_EntropyAssessment
> ) tools.
 
> Should I be analyzing these files with two columns as-is, or should I be
> splitting the upper and lower bounds and analyzing them separately?

You need a small converter app that performs the following for each column of 
values independently (i.e. you will get 2 entropy statements with the 
SP800-90B tool, one for the regular case and one for the estimation of the 
absolute lower boundary):

1. read the integer and truncate it to the amount of least-significant-bits 
(LSB) you want to validate. Usually I only take the 8 LSB or 4 LSB considering 
that the Markov test cannot handle larger bit sizes: parsed_val & 0xff; or 
parsed_val & 0x0f;

2. concatenate the values to form a bit steam and write the data into a file

3. process the data with the SP800-90B tool

4. the resulting data gives you a bit value (either < 1 bits of entropy per 
data bit -> multiply with the number of bits selected in step 1; or you get 
the entropy for the amount of bits - this depends on the chosen options for 
the SP800-90B tool)

The interpretation is the following: The entropy value gives you the amount of 
entropy in that 4 or 8 data bits (as selected in step 1). However, the real 
input data is one time delta value where all bits above the LSB selected in 
step 1 are treated to have zero bits of entropy. I.e. the entropy value 
applies directly to the time delta received by the Jitter RNG.

Knowing that for 64 bits of the Jitter RNG it needs 64 time deltas (assuming 
the oversampling factor is not used), you multiply the entropy value with 64 
to get the number of received entropy for 64 output bits of the Jitter RNG.

Now check the entropy analysis in the Jitter RNG document section 7.2.6 where 
due to the LFSR it is required that each time delta should have at least a bit 
more than 1 bit of entropy. If you can confirm that, you conclude that the 64 
bit output data holds (almost) 64 bit of entropy.
 
> Thanks so much for your help Stephan.
> 
> - Andrew
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/smuellerDD/jitterentropy-library/issues/17


Ciao
Stephan
