### ISSUE TITLE
v3.0.0 and JENT_CONF_ENABLE_INTERNAL_TIMER

### ISSUE THREAD

**Issue by abelbeck** [smuellerDD/jitterentropy-library#19]
@smuellerDD : I tested v3.0.0 on two boxes that rely on  `jitterentropy-library` as a `rngd` (rng-tools) source.

Question, should `JENT_CONF_ENABLE_INTERNAL_TIMER` be disabled if the kernel has `CONFIG_HIGH_RES_TIMERS=y` ?

Entropy rate test: `rngd -t -x hwrng -x rdrand`
```
CPU: Intel(R) Atom(TM) CPU D525 @ 1.80GHz
Linux pbx 4.19.160-astlinux #1 SMP PREEMPT Sat Nov 28 00:12:07 CST 2020 x86_64 GNU/Linux
Kernel Config: CONFIG_HIGH_RES_TIMERS=y

jitterentropy-library: 2.2.0
Entropy rate:  104.6 Kbits/sec averaged over 107 iterations for    155 seconds

jitterentropy-library: 3.0.0 (default w/JENT_CONF_ENABLE_INTERNAL_TIMER)
Entropy rate:  55.63 Kbits/sec averaged over 157 iterations for    185 seconds

jitterentropy-library: 3.0.0 (patched w/o JENT_CONF_ENABLE_INTERNAL_TIMER)
Entropy rate:  113.6 Kbits/sec averaged over 112 iterations for    130 seconds
```
```
CPU: AMD GX-412TC SOC @ 1.0GHz (PC Engines APU2)
Linux pbx4 4.19.160-astlinux #1 SMP PREEMPT Fri Nov 27 14:02:58 CST 2020 x86_64 GNU/Linux
Kernel Config: CONFIG_HIGH_RES_TIMERS=y

jitterentropy-library: 2.2.0
Entropy rate:  51.69 Kbits/sec averaged over 66 iterations for    102 seconds

jitterentropy-library: 3.0.0 (default w/JENT_CONF_ENABLE_INTERNAL_TIMER)
Entropy rate:  58.45 Kbits/sec averaged over 123 iterations for    142 seconds

jitterentropy-library: 3.0.0 (patched w/o JENT_CONF_ENABLE_INTERNAL_TIMER)
Entropy rate:  115.1 Kbits/sec averaged over 82 iterations for    103 seconds
```
Nice improvement for the APU2 box.

**Comment by smuellerDD** [comment]
Am Samstag, 5. Dezember 2020, 22:42:05 CET schrieb Lonnie Abelbeck:

Hi Lonnie,

> @smuellerDD : I tested v3.0.0 on two boxes that rely on 
> `jitterentropy-library` as a `rngd` (rng-tools) source.
> 
> Question, should `JENT_CONF_ENABLE_INTERNAL_TIMER` be disabled if the kernel
> has `CONFIG_HIGH_RES_TIMERS=y` ?

This does not matter. If the option is enabled, the fall-back code is 
compiled. During initialization the libray checks if a high-res timer is 
available. If it is, the internal timer is not used and is simply dead code.

Besides, the kernel configuration should not matter for the timer at least on 
x86, because the library uses RDTSC directly.

Thus, enabling this option on systems with high-res timer simply adds dead 
code. But it is there in case somehow the timer source is degraded (e.g. if 
you run in a VMM and you update your hypervisor which then adds logic to make 
the hardware timer more coarse).

But thank you for your numbers below. They highlight a bug in the code. When 
compiling with JENT_CONF_ENABLE_INTERNAL_TIMER it missed a check to make it 
complete dead code.

I have now fixed it with [1] and it now truly should not matter whether the 
internal timer is compiled or not.

If you use the patch, you will see the same performance on your system 
irrespective whether you compile with or without the internal timer support.

Thanks for the report.

> 
> Entropy rate test: `rngd -t -x hwrng -x rdrand`
> ```
> CPU: Intel(R) Atom(TM) CPU D525 @ 1.80GHz
> Linux pbx 4.19.160-astlinux #1 SMP PREEMPT Sat Nov 28 00:12:07 CST 2020
> x86_64 GNU/Linux Kernel Config: CONFIG_HIGH_RES_TIMERS=y
> 
> jitterentropy-library: 2.2.0
> Entropy rate:  104.6 Kbits/sec averaged over 107 iterations for    155
> seconds
> 
> jitterentropy-library: 3.0.0 (default w/JENT_CONF_ENABLE_INTERNAL_TIMER)
> Entropy rate:  55.63 Kbits/sec averaged over 157 iterations for    185
> seconds
> 
> jitterentropy-library: 3.0.0 (patched w/o JENT_CONF_ENABLE_INTERNAL_TIMER)
> Entropy rate:  113.6 Kbits/sec averaged over 112 iterations for    130
> seconds ```
> ```
> CPU: AMD GX-412TC SOC @ 1.0GHz (PC Engines APU2)
> Linux pbx4 4.19.160-astlinux #1 SMP PREEMPT Fri Nov 27 14:02:58 CST 2020
> x86_64 GNU/Linux Kernel Config: CONFIG_HIGH_RES_TIMERS=y
> 
> jitterentropy-library: 2.2.0
> Entropy rate:  51.69 Kbits/sec averaged over 66 iterations for    102
> seconds
> 
> jitterentropy-library: 3.0.0 (default w/JENT_CONF_ENABLE_INTERNAL_TIMER)
> Entropy rate:  58.45 Kbits/sec averaged over 123 iterations for    142
> seconds
> 
> jitterentropy-library: 3.0.0 (patched w/o JENT_CONF_ENABLE_INTERNAL_TIMER)
> Entropy rate:  115.1 Kbits/sec averaged over 82 iterations for    103
> seconds ```
> Nice improvement for the APU2 box.


Ciao
Stephan

**Comment by abelbeck** [comment]
Hi @smuellerDD : I can confirm 70441d68 fixed this.  Thanks!
