### ISSUE TITLE
[SP 800-90B] The implemented APT test isn't the described SP 800-90B test

### ISSUE THREAD

**Issue by joshuaehill** [smuellerDD/jitterentropy-library#24]
In jent_stuck, the APT test is provided with only the lower 4 bits of the raw data rather than the full raw timer delta sample. If the full raw sample is considered to be the full 64-bit timer delta, then this isn't the behavior described in SP 800-90B. 

This makes the implemented APT test a developer-defined health test (and not an instance of the approved health test, which is how your paper describes it). In validation, this health test must be shown to satisfy SP 800-90B Section 4.5 requirement (b) requirement (which it likely does). This variation also makes the calculated false reject rate (alpha) for this test incorrect.

If the full raw sample is considered to be the low order nibble of the 64-bit timer delta, then the RCT is instead (additionally) non-compliant for this same reason.

**Comment by smuellerDD** [comment]
Am Sonntag, 7. März 2021, 23:31:22 CET schrieb Joshua E. Hill:

Hi Joshua,

> In jent_stuck, the APT test is provided with only the lower 4 bits of the
> raw data rather than the full raw timer delta sample. If the full raw
> sample is considered to be the full 64-bit timer delta, then this isn't the
> behavior described in SP 800-90B. (If the full raw sample is considered to
> be something other than the full 64-bit timer delta, then the RCT is
> instead non-compliant).

The full raw sample is THE time delta.
> 
> This makes the implemented APT test a developer-defined health test that
> must satisfy the SP 800-90B Section 4.5 requirement (b) requirement (which
> it likely does), and makes the calculated false reject rate (alpha)
> incorrect.

I cannot follow the argument: the chosen approach performs the APT not on the 
full value but rather on a small chunk of it. Its likelihood that an alarm is 
triggered is much higher than when using the full time delta value. So, from 
the mathematical side, I cannot follow the argument.

Then, from the true compliance point of view, where would my approach be not 
compliant?

So, what you are saying is that I should remove the masking to be compliant. 
The actual APT implementation, however is consistent. But then, rest assured 
that APT will cause an alarm with much less likelihood since the input data 
variations are much higher.  Thus, I do not understand that comment.

Ciao
Stephan

**Comment by joshuaehill** [comment]
It's just not the APT specified in SP 800-90B Section 4.4.2. Your implemented APT-variant is compliant with Section 4.5 requirement (b) when viewed as a developer-defined health test, as the failure modes of your test are clearly a superset of the 90B-specified version of the test. 

The take away here is that I suggest that you should either change the health test implementation, or describe it differently in your paper (and determine another way to relate the cutoff you have chosen and the value you have selected for alpha).

**Comment by smuellerDD** [comment]
Masking removed.
