### ISSUE TITLE
Very low raw entropy (runtime) results

### ISSUE THREAD

**Issue by dmcdonald167** [smuellerDD/jitterentropy-library#49]
Using jitterentropy-library-3.0.2 on x86_64 running Linux. I got my results with recording_userspace (unmodified) and got these results:

0F_4bits.single: min(H_original, 4 X H_bitstring): 0.085401
0F_4bits.var: min(H_original, 4 X H_bitstring): 0.056432
FF_8bits.single: min(H_original, 8 X H_bitstring): 0.085450
FF_8bits.var: min(H_original, 8 X H_bitstring): 0.056459

Is it just me, or do these results  seem a bit low?  What puzzles me is the conditioned results (with ea_non_iid) look good: 
h': 0.876988

**Comment by smuellerDD** [comment]
Am Donnerstag, dem 17.06.2021 um 05:36 -0700 schrieb dmcdonald167:
> Using jitterentropy-library-3.0.2 on x86_64 running Linux. I got my results
> with recording_userspace and analyzed with validation-runtime using all the
> defaults (except modifying the path to 'ea_iid' and 'ea_non_iid').
> 
> 0F_4bits.single: min(H_original, 4 X H_bitstring): 0.085401
> 0F_4bits.var: min(H_original, 4 X H_bitstring): 0.056432
> FF_8bits.single: min(H_original, 8 X H_bitstring): 0.085450
> FF_8bits.var: min(H_original, 8 X H_bitstring): 0.056459

Indeed, this is a bit low. It looks like you have a coarse timer. Do you have
any hypervisor underneath that alters the RDTSC output?
> 
> Is it just me, or do these results  seem a bit low?  What puzzles me is the
> conditioned results (with ea_non_iid) look good: 
> h': 0.876988

Validating the conditioned entropy is meaningless as you only test that the
SHA-3 operation is good. It does not tell you anything about the available
entropy.
> 
>

**Comment by dmcdonald167** [comment]
> Do you have
any hypervisor underneath that alters the RDTSC output?

Not sure what you mean.  I am running a vanilla Ubuntu 16.04, but not as a virtual machine.
The output of clocksource0/current_clocksource is 'tsc'.   Not sure if that helps.

**Comment by smuellerDD** [comment]
Am Donnerstag, dem 17.06.2021 um 07:01 -0700 schrieb dmcdonald167:
> > Do you have
> any hypervisor underneath that alters the RDTSC output?
> 
> Not sure what you mean.  I am running a vanilla Ubuntu 16.04, but not as a
> virtual machine.
> The output of clocksource0/current_clocksource is 'tsc'.   Not sure if that
> helps.
> 

You may undef JENT_CONF_DISABLE_LOOP_SHUFFLE. This define is a safety
measurement suggested by mathematicians. It used to be enabled in the past,
but I disabled it per default as requested by mathematicians.

Ciao
Stephan

**Comment by dmcdonald167** [comment]
With JENT_CONF_DISABLE_LOOP_SHUFFLE undef'ed, I get:

0F_4bits.single: min(H_original, 4 X H_bitstring): 0.066233
0F_4bits.var: min(H_original, 4 X H_bitstring): 1.197111
FF_8bits.single: min(H_original, 8 X H_bitstring): 0.066271
FF_8bits.var: min(H_original, 8 X H_bitstring): 4.549611

**Comment by smuellerDD** [comment]
Am Donnerstag, dem 17.06.2021 um 07:41 -0700 schrieb dmcdonald167:
> With JENT_CONF_DISABLE_LOOP_SHUFFLE undef'ed, I get:
> 
> 0F_4bits.single: min(H_original, 4 X H_bitstring): 0.066233
> 0F_4bits.var: min(H_original, 4 X H_bitstring): 1.197111
> FF_8bits.single: min(H_original, 8 X H_bitstring): 0.066271
> FF_8bits.var: min(H_original, 8 X H_bitstring): 4.549611
> 

And the var values are the ones that depict what is happening during runtime.

Ciao
Stephan

**Comment by dmcdonald167** [comment]
What value should the 'var' values be in order to produce good entropy?
If I understand correctly, 256 time deltas are needed to produce one 256-bit conditioned result.
So does that mean that any 'var' value above 1.0 is acceptable?

**Comment by smuellerDD** [comment]
Am Donnerstag, dem 17.06.2021 um 07:45 -0700 schrieb dmcdonald167:
> What value should the 'var' values be in order to produce good entropy?
> If I understand correctly, 256 time deltas are needed to produce one 256-bit
> conditioned result.
> So does that mean that any 'var' value above 1.0 is acceptable?
> 

With your current configuration, that is correct.

**Comment by joshuaehill** [comment]
When you remove `JENT_CONF_DISABLE_LOOP_SHUFFLE` you still essentially have the same level of entropy as you did before, but the low entropy condition is masked.

It seems a better idea to explore why this problem is arising. Have you compiled the library using an optimizer? This has led to problems in the past (see issue #21). Could you provide your data sample?

**Comment by dmcdonald167** [comment]
Hi Joshua,
The main jitterentropy-library Makefile is untouched and has optimisation left at -O0.

I have put my samples and results here: https://github.com/dmcdonald167/jcpu-results

**Comment by joshuaehill** [comment]
There are a large number of long repeated substrings, which suggests that there is a significant deterministic component to the variation. A few things to consider trying:

For the current system, you can satisfy the underlying assumptions in the library by setting `osr` to 14 or higher; the library makes the assumption that `H≥1/osr`, so adjusting this value is a natural portion of using this library.

To increase the per-raw sample entropy, you can try a couple of approaches: 

1. It may be useful to increase the return value of `jent_loop_shuffle` to its maximum value `(1U<<min)+(1U<<bits)-1)` instead of its minimum value of `(1U<<min)`. 
2. You can also increase the memory cache churn by using the Lag Predictor Health Test (PR #47) and increasing `JENT_LAG_HISTORY_SIZE` to some larger size, like 128; note this value must be a power of 2.

Let me know if you have any questions.

**Comment by smuellerDD** [comment]
Am Donnerstag, 17. Juni 2021, 15:07:53 CEST schrieb Stephan Mueller:

Hi,

> Am Donnerstag, dem 17.06.2021 um 05:36 -0700 schrieb dmcdonald167:
> > Using jitterentropy-library-3.0.2 on x86_64 running Linux. I got my
> > results
> > with recording_userspace and analyzed with validation-runtime using all
> > the
> > defaults (except modifying the path to 'ea_iid' and 'ea_non_iid').
> > 
> > 0F_4bits.single: min(H_original, 4 X H_bitstring): 0.085401
> > 0F_4bits.var: min(H_original, 4 X H_bitstring): 0.056432
> > FF_8bits.single: min(H_original, 8 X H_bitstring): 0.085450
> > FF_8bits.var: min(H_original, 8 X H_bitstring): 0.056459
> 
> Indeed, this is a bit low. It looks like you have a coarse timer. Do you
> have any hypervisor underneath that alters the RDTSC output?
> 
> > Is it just me, or do these results  seem a bit low?  What puzzles me is
> > the
> > conditioned results (with ea_non_iid) look good:
> > h': 0.876988
> 
> Validating the conditioned entropy is meaningless as you only test that the
> SHA-3 operation is good. It does not tell you anything about the available
> entropy.

There is one solution that you can try without disabling 
JENT_CONF_DISABLE_LOOP_SHUFFLE.

I finally found a system that has meager entropy from the regular code base - 
my new RISC-V system. 

The solution was to adjust the memory access such that it will definitely hit 
L2 cache by increasing JENT_MEMORY_BLOCKS. On my RISC-V, I used 2048 and got 
ample entropy from that. At least sufficient for the Jitter RNG.

The total amount of memory allocated for the Jitter RNG is defined by 
JENT_MEMORY_SIZE. So, if you do not have memory pressure, I would try with 
2048 or 4096 depending on your L1 size. It would be great if you could report 
how you fare.

Ciao
Stephan

**Comment by dmcdonald167** [comment]
> I would try with 2048 or 4096 depending on your L1 size.
I have two cores.  One shows L1 cache as 32KiB, and the other as 24KiB.  I tried JENT_MEMORY_BLOCKS as 2048 and 4096 and the results are below:

JENT_MEMORY_BLOCKS = 2048

min(H_original, 4 X H_bitstring): 0.259410
min(H_original, 4 X H_bitstring): 0.185153
min(H_original, 8 X H_bitstring): 0.263580
min(H_original, 8 X H_bitstring): 0.185153

JENT_MEMORY_BLOCKS = 4096

min(H_original, 4 X H_bitstring): 0.154473
min(H_original, 4 X H_bitstring): 0.183042
min(H_original, 8 X H_bitstring): 0.154404
min(H_original, 8 X H_bitstring): 0.200166

**Comment by dmcdonald167** [comment]
Ok I just tried some very different parameters:

```
#define JENT_MEMORY_BLOCKS 8192
#define JENT_MEMORY_BLOCKSIZE 128
```

And I got these results: 

```
min(H_original, 4 X H_bitstring): 1.185871
min(H_original, 4 X H_bitstring): 1.190238
min(H_original, 8 X H_bitstring): 4.062310
min(H_original, 8 X H_bitstring): 4.474649
```

**Comment by dmcdonald167** [comment]
Sorry Joshua for my slow reply on this:

> For the current system, you can satisfy the underlying assumptions in the library by setting `osr` to 14 or higher; the library makes the assumption that `H≥1/osr`, so adjusting this value is a natural portion of using this library.

I tried increasing `JENT_MIN_OSR` to `14` but didn't notice any real improvement.  I noticed that this parameter affects how `jent_random_data()` collects data, but does not affect the `jitterentropy-hashtime` program, which calls `jent_one_test()` repeatedly.  Perhaps this is why I didn't notice any difference?  (Please correct me if I'm way off).

> 1. It may be useful to increase the return value of `jent_loop_shuffle` to its maximum value `(1U<<min)+(1U<<bits)-1)` instead of its minimum value of `(1U<<min)`.

I gave this a whirl and didn't notice any improvement either.

> 2. You can also increase the memory cache churn by using the Lag Predictor Health Test (PR #41) and increasing `JENT_LAG_HISTORY_SIZE` to some larger size, like 128; note this value must be a power of 2.

Yet to give this a try.  I'll get back to you on this one.

**Comment by smuellerDD** [comment]
Am Sonntag, 20. Juni 2021, 14:11:42 CEST schrieb dmcdonald167:

Hi dmcdonald167,

> Sorry Joshua for my slow reply on this:
> 
> 
> > For the current system, you can satisfy the underlying assumptions in the
> > library by setting `osr` to 14 or higher; the library makes the
> > assumption that `H≥1/osr`, so adjusting this value is a natural portion
> > of using this library.
> 
> I tried increasing `JENT_MIN_OSR` to `14` but didn't notice any real
> improvement.  I noticed that this parameter affects how
> `jent_random_data()` collects data, but does not affect the
> `jitterentropy-hashtime` program, which calls `jent_one_test()` repeatedly.
>  Perhaps this is why I didn't notice any difference?  (Please correct me if
> I'm way off).

Correct.
 
> 
> > 1. It may be useful to increase the return value of `jent_loop_shuffle` to
> > its maximum value `(1U<<min)+(1U<<bits)-1)` instead of its minimum value
> > of `(1U<<min)`.
> 
> I gave this a whirl and didn't notice any improvement either.

I do not think this will help either. I think your results with the memory 
access is consistent with my research. Thank you for providing this data.
> 
> 
> > 2. You can also increase the memory cache churn by using the Lag Predictor
> > Health Test (PR #41) and increasing `JENT_LAG_HISTORY_SIZE` to some
> > larger size, like 128; note this value must be a power of 2.
> 
> Yet to give this a try.  I'll get back to you on this one.

Note, the current upstream code does not (yet) have this option. Only Josh's 
patches.

Ciao
Stephan
> 
> 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/smuellerDD/jitterentropy-library/issues/49#issuecomment-8
> 64544653


Ciao
Stephan

**Comment by joshuaehill** [comment]
@dmcdonald167 Thank you for your feedback regarding increasing the loop count output from `jent_loop_shuffle`. The anticipated situation where this might help is one where variations induced by external events are a significant contributor to the uncertainty (as this change increases the amount of time where such events could occur and impact the library's timing). It appears that for your test system, the variation is driven mostly by internal microarchitectural effects, and in this case increasing the number of loops only translates the delta distribution to the right, and doesn't significantly increase the resulting variation.

As both you and @smuellerDD mentioned, the `osr` value only changes the amount that is fed into the conditioning, so it makes it so that your conditioned output should have the amount of entropy that is claimed. This value does not impact the generation of the raw samples, and so would not impact the results of your statistical testing.

**Comment by dmcdonald167** [comment]
Thanks @joshuaehill and @smuellerDD, I think this answers all the questions I had.

**Comment by smuellerDD** [comment]
For the sake of discussion, I added test helpers allowing to validate a large array of different memory buffer sizes. On my RISC-V on which the Jitter RNG collected insufficient entropy, I found the settings that provided sufficient entropy.

The test README now is updated to explain steps in case the Jitter RNG finds too little entropy by using the mentioned tools.

Based on this test result I increased the memory buffer size to 512 kBytes.

I also changed the code such that you can modify the memory buffer size by adding your own CFLAGS options instead of altering the header file.

Thanks for your help.
