### ISSUE TITLE
restart test, why collect two column data

### ISSUE THREAD

**Issue by yuyinw** [smuellerDD/jitterentropy-library#53]
hello,
   i have a question need your help ,  i see  two times data (**duration, duration_min**) are collected in the  at   function  **jent_one_test** (jitterentropy_lfsrtime.c) , why  use two timestarmps,   i  see  90b  describe (1000 * 1000),  i understand just need collect one time data.

thank you

**Comment by smuellerDD** [comment]
Am Mittwoch, 7. Juli 2021, 10:34:36 CEST schrieb yuyinw:

Hi yuyinw,

> hello,
>    i have a question need your help ,  i see  two times data (**duration,
> duration_min**) are collected in the  at   function  **jent_one_test**
> (jitterentropy_lfsrtime.c) , why  use two timestarmps,   i  see  90b 
> describe (1000 * 1000),  i understand just need collect one time data.

With the current code base, this is not of interest any more. But if you 
disable JENT_CONF_DISABLE_LOOP_SHUFFLE the "var" values give you the data 
returned by the regular operation of the Jitter RNG and the "signle" value 
give you the worst-case values.
> 
> 
> thank you


Ciao
Stephan

**Comment by yuyinw** [comment]
thank you very much

**Comment by yuyinw** [comment]
Hello
    when  i get runing time result ,
    H_original: 6.442681
    H_bitstring: 0.605177
    min(H_original, 8 X H_bitstring): 4.841414
i can  think  the 64 bit entropy pool can  generate 64 bit entropy , when i  use jent_read_entropy  get  64type(256bit data) ,  can i think  the out entropy entropy  is    256bit

**Comment by smuellerDD** [comment]
Am Montag, 12. Juli 2021, 13:58:56 CEST schrieb yuyinw:

Hi yuyinw,

> Hello
>     when  i get runing time result ,
>     H_original: 6.442681
>     H_bitstring: 0.605177
>     min(H_original, 8 X H_bitstring): 4.841414
> i can  think  the 64 bit entropy pool can  generate 64 bit entropy , when i 
> use jent_read_entropy  get  64type(256bit data) ,  can i think  the out
> entropy entropy  is    256bit

With the given measurement, you can conclude that one time delta produces at 
least 4.8 bits of entropy.

The Jitter RNG collects:

- 2.x: 64 time deltas to produce 64 output bits per block

- < 3.0.2: 256 time deltas to produce 256 output bits per block

- >= 3.0.2: 768 time deltas to produce 256 output bits per block

In any case, the output block should therefore be considered to have full 
entropy.

Ciao
Stephan

**Comment by yuyinw** [comment]
Thank you very mch.  
In summarize, we calculate the minimum entropy of  the output entropy  at  running time test,  we get the result : min(H_original, 8 X H_bitstring): 7.981223, almost 1bit entropy of 1bit output.  So i can get the result the out entropy entropy is 256bit  when   i use jent_read_entropy get 64type(256bit data).

**Comment by joshuaehill** [comment]
The post-conditioned data output from this library cannot be meaningfully statistically assessed because it is the output of a PRF (SHA3-256). 

If this is what you did to produce the result that you cite, then that result essentially gives you no information about entropy level being output, and only provides you insight into the underlying NIST tests (in particular, their maximum value).

If you are going through a 90B validation, then you would estimate the output entropy using the procedure in SP 800-90B Section 3.1.5.1.2 (there is a tool to perform the calculation in the NIST tool: `ea_conditioning`). If you are not going through this process, then you could consider the output as full entropy so long as the per-symbol raw entropy assessment that you arrive at is greater than or equal to `1/osr`. (The default value for `osr` is 3, but this can be set when you allocate the entropy source).

**Comment by yuyinw** [comment]
Thank  you joshuaehill !

My version  Jitter 2.1.0 (osr = 1) ,and  i  calculate  raw entropy with running time test , and get the result min(H_original, 8 X H_bitstring): 4.841414 , so i can prove  64 time deltas to produce 64 output bits per block. 

And i  also  using the runing time script,  calcuate the output enptropy    min(H_original, 8 X H_bitstring): 7.981223, pass IID permutation tests

 
So can i  get the result the out entropy entropy is 256bit when i use jent_read_entropy get 64type(256bit data).

**Comment by joshuaehill** [comment]
The fact that the output passes IID testing isn't relevant to anything; that version's output is the output of an LFSR, which produces statistically excellent looking output irrespective of input. One can only conclude results about IID on the raw data. There is no reason to think that this raw data is IID, and I'd need to be granted some sort of mind-blowing insight into the system to believe that this could maybe be true. I presently think that the raw data is almost certainly non-IID, which means that the conditioned data should also be treated as non-IID.

As it turns out in a 90B validation with this version of the library, one is required to perform statistical testing on the output (LFSRs are considered a non-vetted conditioning function), but this still isn't likely to be a particularly meaningful result.

If you are asking for my opinion as to whether v2.1.0 output is definitely full entropy given your test results, I'd say that it isn't really clear; are your stated results based on analysis of column 1 or column 2 raw test data? If column 2, then my answer would be "maybe" (though I'd want to take a look at the performance of sub-distributions in the raw data). If those results are using column 1 of the raw data, then I don't think that you can draw very much from those results (as the pseudorandom variation included in this version renders statistical assessment much less meaningful).

My specific guidance is that v3.0.2 is dramatically more conservative than v2.1.0, and v3.1.0 (when it is released) even more so. You should probably default to using a more conservative version of the library, unless you have some specific reason for not doing so.

**Comment by yuyinw** [comment]
Thank you joshuaehill !

There are some special reasons why our project has been using this version Jitter v2.1.0.

I also double the IID Result .  I've seen this conclusion (No entropy source in this universe is IID and so claiming it and testing for it is just stupid) .

Validation-runtime  IID test  : the data is collected  by compile and run  jitterentropy-lfsroutput.c ( collect  1000000* 32 byte through jent_read_entropy()),   It doesn't seem to distinguish  single and var  data .  But the results are stored in jent-conditioned.minentropy_8.var  ：

Opening file: '../results-measurements/jent-conditioned.data'
Loaded 32000000 samples of 256 distinct 8-bit-wide symbols
Number of Binary samples: 256000000
Calculating baseline statistics...
	Raw Mean: 127.503014
	Median: 128.000000
	Binary: false

Literal MCV Estimate: mode = 125726, p-hat = 0.0039289375000000001, p_u = 0.0039574230637579588
Bitstring MCV Estimate: mode = 128002076, p-hat = 0.50000810937499995, p_u = 0.50008860404088251
H_original: 7.981223
H_bitstring: 0.999744
min(H_original, 8 X H_bitstring): 7.981223

**Comment by smuellerDD** [comment]
Am Freitag, 16. Juli 2021, 04:35:27 CEST schrieb yuyinw:

Hi yuyinw,

> Thank you joshuaehill !
> 
> There are some special reasons why our project has been using this version
> Jitter v2.1.0.
 
> I also double the IID Result .  I've seen this conclusion (No entropy source
> in this universe is IID and so claiming it and testing for it is just
> stupid) .
 
> Validation-runtime  IID test  : the data is collected  by compile and run 
> jitterentropy-lfsroutput.c ( collect  1000000* 32 byte through
> jent_read_entropy()),   It doesn't seem to distinguish  single and var 
> data .  But the results are stored in jent-conditioned.minentropy_8.var  ：

After conditioning, there is no reason to distinguish between those two. All 
data is now post-conditioning where the respective differences in the raw 
entropy data are gone.
> 
> Opening file: '../results-measurements/jent-conditioned.data'
> Loaded 32000000 samples of 256 distinct 8-bit-wide symbols
> Number of Binary samples: 256000000
> Calculating baseline statistics...
> 	Raw Mean: 127.503014
> 	Median: 128.000000
> 	Binary: false
> 
> Literal MCV Estimate: mode = 125726, p-hat = 0.0039289375000000001, p_u =
> 0.0039574230637579588
 Bitstring MCV Estimate: mode = 128002076, p-hat =
> 0.50000810937499995, p_u = 0.50008860404088251 H_original: 7.981223
> H_bitstring: 0.999744
> min(H_original, 8 X H_bitstring): 7.981223

As Josh mentioned, this test only verifies that the LFSR worked as intended. 
You get similar results when you feed a monotonic increasing number into the 
LFSR. Thus, the test result should only be interpreted as that: the LFSR does 
(almost) not destroy entropy during the compression operation.

But you cannot deduct the entropy rate from the result.

Ciao
Stephan
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/smuellerDD/jitterentropy-library/issues/53#issuecomment-8
> 81132931


Ciao
Stephan

**Comment by yuyinw** [comment]
Thank you  smuellerDD.
         It seems all the test just prove the entropy pool  is full of entropy。But  when i  use   CPU Jitter  as  a entropy  source  for  TRBG,   how can i   prove the output entropy  of CPU jitter is more than 256 bit ?  （i used to think  the out entropy entropy is 256bit when i use jent_read_entropy get 64type(256bit data)）

**Comment by smuellerDD** [comment]
Am Freitag, dem 16.07.2021 um 05:08 -0700 schrieb yuyinw:
> Thank you  smuellerDD.
>          It seems all the test just prove the entropy pool  is full of
> entropy。But  when i  use   CPU Jitter  as  a entropy  source  for  TRBG,  
> how can i   prove the output entropy  of CPU jitter is more than 256 bit ? 
> （i used to think  the out entropy entropy is 256bit when i use
> jent_read_entropy get 64type(256bit data)）

To verify that you have sufficient entropy, you use the tool set part of the
current upstream code base, tests/raw-entropy/recording_userspace.

Read README.md to understand how the test is executed and the results are
interpreted.

That should hopefully show you that you get almost 64 bits of entropy for each
64 bit block from the Jitter RNG 2.x. If you need 256 bits of entropy, you
obtain, say, 5 blocks from the Jitter RNG == 320 bits of data with maybe 310
bits of entropy.

Ciao
Stephan

**Comment by yuyinw** [comment]
Thank you smuellerDD !
Thank you joshuaehill !

I think i understand it .  

With the running time test , we the prove that 64 time deltas to produce 64 output bits per block . 

And  because  LFSRs are considered a non-vetted conditioning function , so  the entropy of the conditioned output is estimated as  63 bit  ( calculte at  pdf  7.2.6 SP800-90B Section 3.1.5.2),  so  if we  need 256 bits of entropy,  we need  5 blocks (  use jent_read_entropy get 45 type(320bit data) )  at least.  (320/64*63  > 256 )

With the running time test , we the prove that 64 time deltas to produce 64 output bits per block . 

And  because  LFSRs are considered a non-vetted conditioning function , so  the entropy of the conditioned output is estimated as  63 bit  ( calculte at  pdf  7.2.6 SP800-90B Section 3.1.5.2),  so  if we  need 256 bits of entropy,  we need  5 blocks (  use jent_read_entropy get 45 type(320bit data) )  at least.  (320/64*63  > 256 )

**Comment by yuyinw** [comment]
Thank you smuellerDD !
Thank you joshuaehill !

I think i understand it .  

With the running time test , we the prove that 64 time deltas to produce 64 output bits per block . 

And  because  LFSRs are considered a non-vetted conditioning function , so  the entropy of the conditioned output is estimated as  63 bit  ( calculte at  pdf  7.2.6 SP800-90B Section 3.1.5.2),  so  if we  need 256 bits of entropy,  we need  5 blocks (  use jent_read_entropy get 45 type(320bit data) )  at least.  (320/64*63  > 256 )
